### ISSUE TITLE
Card got its ease>250% even though "stop at ease" is 250%

### ISSUE THREAD

**Issue by destel** [hgiesel/anki_straight_reward#4] opened 2020-03-13 12:49 UTC
Below are screenshots of settings, card info and relevant piece of log

<img width="393" alt="Screenshot 2020-03-13 at 14 44 56" src="https://user-images.githubusercontent.com/2601311/76622157-a12f6300-6539-11ea-8048-170f5e202b7e.png">

<img width="643" alt="Screenshot 2020-03-13 at 10 24 08" src="https://user-images.githubusercontent.com/2601311/76622189-ad1b2500-6539-11ea-8d8e-a2cf87138018.png">

```
### Ease Changes applied in collection 1575079200 on 2020-03-13 09:58:17.326462:
...
1579275228229: Default: 15
...
```

**Comment by hgiesel** [comment] 2020-03-13 17:54
Is this only for the sync hook?

**Comment by destel** [comment] 2020-03-13 17:58
Yes, it's sync hook

**Comment by hgiesel** [comment] 2020-03-15 18:06
The review_hook and the sync_hook use the same logic in this case. I have the suspicion that it's caused by using Easy on Mobile: The cards gets an ease bonus per se, but the add-on awards the ease before the first one is applied.

Anyway, I'll wait till the other issue is fixed.

**Comment by hgiesel** [comment] 2020-05-04 03:00
Haven't seen this issue in a very long time, which is why I'm closing this now.

**Closed by hgiesel** 2020-05-04 03:00 UTC
Labels: bug
